services:
    noordo.hide.listener:
        class: noordo\hide\event\listener
        arguments:
            - '@noordo.hide.helper'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@user'
        tags:
            - { name: event.listener }

    noordo.hide.helper:
        class: noordo\hide\includes\helper
        arguments:
            - '@dbal.conn'
            - '@filesystem'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
